// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kofalt/example-ent-crdb/ent/predicate"
	"github.com/kofalt/example-ent-crdb/ent/ride"
	"github.com/kofalt/example-ent-crdb/ent/user"
	"github.com/kofalt/example-ent-crdb/ent/vehicle"
	"github.com/kofalt/example-ent-crdb/ent/vehiclelocationhistory"
)

// RideQuery is the builder for querying Ride entities.
type RideQuery struct {
	config
	ctx                          *QueryContext
	order                        []OrderFunc
	inters                       []Interceptor
	predicates                   []predicate.Ride
	withUser                     *UserQuery
	withVehicle                  *VehicleQuery
	withVehicleLocationHistories *VehicleLocationHistoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RideQuery builder.
func (rq *RideQuery) Where(ps ...predicate.Ride) *RideQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RideQuery) Limit(limit int) *RideQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RideQuery) Offset(offset int) *RideQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RideQuery) Unique(unique bool) *RideQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RideQuery) Order(o ...OrderFunc) *RideQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryUser chains the current query on the "user" edge.
func (rq *RideQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ride.Table, ride.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ride.UserTable, ride.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVehicle chains the current query on the "vehicle" edge.
func (rq *RideQuery) QueryVehicle() *VehicleQuery {
	query := (&VehicleClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ride.Table, ride.FieldID, selector),
			sqlgraph.To(vehicle.Table, vehicle.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ride.VehicleTable, ride.VehicleColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVehicleLocationHistories chains the current query on the "vehicle_location_histories" edge.
func (rq *RideQuery) QueryVehicleLocationHistories() *VehicleLocationHistoryQuery {
	query := (&VehicleLocationHistoryClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ride.Table, ride.FieldID, selector),
			sqlgraph.To(vehiclelocationhistory.Table, vehiclelocationhistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ride.VehicleLocationHistoriesTable, ride.VehicleLocationHistoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ride entity from the query.
// Returns a *NotFoundError when no Ride was found.
func (rq *RideQuery) First(ctx context.Context) (*Ride, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ride.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RideQuery) FirstX(ctx context.Context) *Ride {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ride ID from the query.
// Returns a *NotFoundError when no Ride ID was found.
func (rq *RideQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ride.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RideQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ride entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ride entity is found.
// Returns a *NotFoundError when no Ride entities are found.
func (rq *RideQuery) Only(ctx context.Context) (*Ride, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ride.Label}
	default:
		return nil, &NotSingularError{ride.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RideQuery) OnlyX(ctx context.Context) *Ride {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ride ID in the query.
// Returns a *NotSingularError when more than one Ride ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RideQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ride.Label}
	default:
		err = &NotSingularError{ride.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RideQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rides.
func (rq *RideQuery) All(ctx context.Context) ([]*Ride, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ride, *RideQuery]()
	return withInterceptors[[]*Ride](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RideQuery) AllX(ctx context.Context) []*Ride {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ride IDs.
func (rq *RideQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err := rq.Select(ride.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RideQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RideQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RideQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RideQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RideQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RideQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RideQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RideQuery) Clone() *RideQuery {
	if rq == nil {
		return nil
	}
	return &RideQuery{
		config:                       rq.config,
		ctx:                          rq.ctx.Clone(),
		order:                        append([]OrderFunc{}, rq.order...),
		inters:                       append([]Interceptor{}, rq.inters...),
		predicates:                   append([]predicate.Ride{}, rq.predicates...),
		withUser:                     rq.withUser.Clone(),
		withVehicle:                  rq.withVehicle.Clone(),
		withVehicleLocationHistories: rq.withVehicleLocationHistories.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RideQuery) WithUser(opts ...func(*UserQuery)) *RideQuery {
	query := (&UserClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withUser = query
	return rq
}

// WithVehicle tells the query-builder to eager-load the nodes that are connected to
// the "vehicle" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RideQuery) WithVehicle(opts ...func(*VehicleQuery)) *RideQuery {
	query := (&VehicleClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withVehicle = query
	return rq
}

// WithVehicleLocationHistories tells the query-builder to eager-load the nodes that are connected to
// the "vehicle_location_histories" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RideQuery) WithVehicleLocationHistories(opts ...func(*VehicleLocationHistoryQuery)) *RideQuery {
	query := (&VehicleLocationHistoryClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withVehicleLocationHistories = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		City string `json:"city,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ride.Query().
//		GroupBy(ride.FieldCity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RideQuery) GroupBy(field string, fields ...string) *RideGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RideGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = ride.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		City string `json:"city,omitempty"`
//	}
//
//	client.Ride.Query().
//		Select(ride.FieldCity).
//		Scan(ctx, &v)
func (rq *RideQuery) Select(fields ...string) *RideSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RideSelect{RideQuery: rq}
	sbuild.label = ride.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RideSelect configured with the given aggregations.
func (rq *RideQuery) Aggregate(fns ...AggregateFunc) *RideSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RideQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !ride.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RideQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ride, error) {
	var (
		nodes       = []*Ride{}
		_spec       = rq.querySpec()
		loadedTypes = [3]bool{
			rq.withUser != nil,
			rq.withVehicle != nil,
			rq.withVehicleLocationHistories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ride).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ride{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withUser; query != nil {
		if err := rq.loadUser(ctx, query, nodes, nil,
			func(n *Ride, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withVehicle; query != nil {
		if err := rq.loadVehicle(ctx, query, nodes, nil,
			func(n *Ride, e *Vehicle) { n.Edges.Vehicle = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withVehicleLocationHistories; query != nil {
		if err := rq.loadVehicleLocationHistories(ctx, query, nodes,
			func(n *Ride) { n.Edges.VehicleLocationHistories = []*VehicleLocationHistory{} },
			func(n *Ride, e *VehicleLocationHistory) {
				n.Edges.VehicleLocationHistories = append(n.Edges.VehicleLocationHistories, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RideQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Ride, init func(*Ride), assign func(*Ride, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Ride)
	for i := range nodes {
		fk := nodes[i].RiderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rider_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *RideQuery) loadVehicle(ctx context.Context, query *VehicleQuery, nodes []*Ride, init func(*Ride), assign func(*Ride, *Vehicle)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Ride)
	for i := range nodes {
		fk := nodes[i].VehicleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vehicle.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vehicle_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *RideQuery) loadVehicleLocationHistories(ctx context.Context, query *VehicleLocationHistoryQuery, nodes []*Ride, init func(*Ride), assign func(*Ride, *VehicleLocationHistory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Ride)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.VehicleLocationHistory(func(s *sql.Selector) {
		s.Where(sql.InValues(ride.VehicleLocationHistoriesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RideID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ride_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *RideQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RideQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ride.Table,
			Columns: ride.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: ride.FieldID,
			},
		},
		From:   rq.sql,
		Unique: true,
	}
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ride.FieldID)
		for i := range fields {
			if fields[i] != ride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RideQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(ride.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = ride.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RideGroupBy is the group-by builder for Ride entities.
type RideGroupBy struct {
	selector
	build *RideQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RideGroupBy) Aggregate(fns ...AggregateFunc) *RideGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RideGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RideQuery, *RideGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RideGroupBy) sqlScan(ctx context.Context, root *RideQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RideSelect is the builder for selecting fields of Ride entities.
type RideSelect struct {
	*RideQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RideSelect) Aggregate(fns ...AggregateFunc) *RideSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RideSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RideQuery, *RideSelect](ctx, rs.RideQuery, rs, rs.inters, v)
}

func (rs *RideSelect) sqlScan(ctx context.Context, root *RideQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
