// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/kofalt/example-ent-crdb/ent/ride"
	"github.com/kofalt/example-ent-crdb/ent/schema"
	"github.com/kofalt/example-ent-crdb/ent/user"
	"github.com/kofalt/example-ent-crdb/ent/userpromocode"
	"github.com/kofalt/example-ent-crdb/ent/vehicle"
	"github.com/kofalt/example-ent-crdb/ent/vehiclelocationhistory"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rideFields := schema.Ride{}.Fields()
	_ = rideFields
	// rideDescID is the schema descriptor for id field.
	rideDescID := rideFields[0].Descriptor()
	// ride.DefaultID holds the default value on creation for the id field.
	ride.DefaultID = rideDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userpromocodeFields := schema.UserPromoCode{}.Fields()
	_ = userpromocodeFields
	// userpromocodeDescID is the schema descriptor for id field.
	userpromocodeDescID := userpromocodeFields[0].Descriptor()
	// userpromocode.DefaultID holds the default value on creation for the id field.
	userpromocode.DefaultID = userpromocodeDescID.Default.(func() uuid.UUID)
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescID is the schema descriptor for id field.
	vehicleDescID := vehicleFields[0].Descriptor()
	// vehicle.DefaultID holds the default value on creation for the id field.
	vehicle.DefaultID = vehicleDescID.Default.(func() uuid.UUID)
	vehiclelocationhistoryFields := schema.VehicleLocationHistory{}.Fields()
	_ = vehiclelocationhistoryFields
	// vehiclelocationhistoryDescID is the schema descriptor for id field.
	vehiclelocationhistoryDescID := vehiclelocationhistoryFields[0].Descriptor()
	// vehiclelocationhistory.DefaultID holds the default value on creation for the id field.
	vehiclelocationhistory.DefaultID = vehiclelocationhistoryDescID.Default.(func() uuid.UUID)
}
