// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kofalt/example-ent-crdb/ent/predicate"
	"github.com/kofalt/example-ent-crdb/ent/userpromocode"
)

// UserPromoCodeDelete is the builder for deleting a UserPromoCode entity.
type UserPromoCodeDelete struct {
	config
	hooks    []Hook
	mutation *UserPromoCodeMutation
}

// Where appends a list predicates to the UserPromoCodeDelete builder.
func (upcd *UserPromoCodeDelete) Where(ps ...predicate.UserPromoCode) *UserPromoCodeDelete {
	upcd.mutation.Where(ps...)
	return upcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (upcd *UserPromoCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, UserPromoCodeMutation](ctx, upcd.sqlExec, upcd.mutation, upcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (upcd *UserPromoCodeDelete) ExecX(ctx context.Context) int {
	n, err := upcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (upcd *UserPromoCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userpromocode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userpromocode.FieldID,
			},
		},
	}
	if ps := upcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, upcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	upcd.mutation.done = true
	return affected, err
}

// UserPromoCodeDeleteOne is the builder for deleting a single UserPromoCode entity.
type UserPromoCodeDeleteOne struct {
	upcd *UserPromoCodeDelete
}

// Where appends a list predicates to the UserPromoCodeDelete builder.
func (upcdo *UserPromoCodeDeleteOne) Where(ps ...predicate.UserPromoCode) *UserPromoCodeDeleteOne {
	upcdo.upcd.mutation.Where(ps...)
	return upcdo
}

// Exec executes the deletion query.
func (upcdo *UserPromoCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := upcdo.upcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpromocode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (upcdo *UserPromoCodeDeleteOne) ExecX(ctx context.Context) {
	if err := upcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
