// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kofalt/example-ent-crdb/ent/predicate"
	"github.com/kofalt/example-ent-crdb/ent/user"
	"github.com/kofalt/example-ent-crdb/ent/userpromocode"
)

// UserPromoCodeQuery is the builder for querying UserPromoCode entities.
type UserPromoCodeQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.UserPromoCode
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserPromoCodeQuery builder.
func (upcq *UserPromoCodeQuery) Where(ps ...predicate.UserPromoCode) *UserPromoCodeQuery {
	upcq.predicates = append(upcq.predicates, ps...)
	return upcq
}

// Limit the number of records to be returned by this query.
func (upcq *UserPromoCodeQuery) Limit(limit int) *UserPromoCodeQuery {
	upcq.ctx.Limit = &limit
	return upcq
}

// Offset to start from.
func (upcq *UserPromoCodeQuery) Offset(offset int) *UserPromoCodeQuery {
	upcq.ctx.Offset = &offset
	return upcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upcq *UserPromoCodeQuery) Unique(unique bool) *UserPromoCodeQuery {
	upcq.ctx.Unique = &unique
	return upcq
}

// Order specifies how the records should be ordered.
func (upcq *UserPromoCodeQuery) Order(o ...OrderFunc) *UserPromoCodeQuery {
	upcq.order = append(upcq.order, o...)
	return upcq
}

// QueryUser chains the current query on the "user" edge.
func (upcq *UserPromoCodeQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: upcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := upcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := upcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userpromocode.Table, userpromocode.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userpromocode.UserTable, userpromocode.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(upcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserPromoCode entity from the query.
// Returns a *NotFoundError when no UserPromoCode was found.
func (upcq *UserPromoCodeQuery) First(ctx context.Context) (*UserPromoCode, error) {
	nodes, err := upcq.Limit(1).All(setContextOp(ctx, upcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userpromocode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) FirstX(ctx context.Context) *UserPromoCode {
	node, err := upcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserPromoCode ID from the query.
// Returns a *NotFoundError when no UserPromoCode ID was found.
func (upcq *UserPromoCodeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upcq.Limit(1).IDs(setContextOp(ctx, upcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userpromocode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := upcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserPromoCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserPromoCode entity is found.
// Returns a *NotFoundError when no UserPromoCode entities are found.
func (upcq *UserPromoCodeQuery) Only(ctx context.Context) (*UserPromoCode, error) {
	nodes, err := upcq.Limit(2).All(setContextOp(ctx, upcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userpromocode.Label}
	default:
		return nil, &NotSingularError{userpromocode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) OnlyX(ctx context.Context) *UserPromoCode {
	node, err := upcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserPromoCode ID in the query.
// Returns a *NotSingularError when more than one UserPromoCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (upcq *UserPromoCodeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upcq.Limit(2).IDs(setContextOp(ctx, upcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userpromocode.Label}
	default:
		err = &NotSingularError{userpromocode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := upcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserPromoCodes.
func (upcq *UserPromoCodeQuery) All(ctx context.Context) ([]*UserPromoCode, error) {
	ctx = setContextOp(ctx, upcq.ctx, "All")
	if err := upcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserPromoCode, *UserPromoCodeQuery]()
	return withInterceptors[[]*UserPromoCode](ctx, upcq, qr, upcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) AllX(ctx context.Context) []*UserPromoCode {
	nodes, err := upcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserPromoCode IDs.
func (upcq *UserPromoCodeQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	ctx = setContextOp(ctx, upcq.ctx, "IDs")
	if err := upcq.Select(userpromocode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := upcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upcq *UserPromoCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, upcq.ctx, "Count")
	if err := upcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, upcq, querierCount[*UserPromoCodeQuery](), upcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) CountX(ctx context.Context) int {
	count, err := upcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upcq *UserPromoCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, upcq.ctx, "Exist")
	switch _, err := upcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (upcq *UserPromoCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := upcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserPromoCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upcq *UserPromoCodeQuery) Clone() *UserPromoCodeQuery {
	if upcq == nil {
		return nil
	}
	return &UserPromoCodeQuery{
		config:     upcq.config,
		ctx:        upcq.ctx.Clone(),
		order:      append([]OrderFunc{}, upcq.order...),
		inters:     append([]Interceptor{}, upcq.inters...),
		predicates: append([]predicate.UserPromoCode{}, upcq.predicates...),
		withUser:   upcq.withUser.Clone(),
		// clone intermediate query.
		sql:  upcq.sql.Clone(),
		path: upcq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (upcq *UserPromoCodeQuery) WithUser(opts ...func(*UserQuery)) *UserPromoCodeQuery {
	query := (&UserClient{config: upcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	upcq.withUser = query
	return upcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		City string `json:"city,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserPromoCode.Query().
//		GroupBy(userpromocode.FieldCity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (upcq *UserPromoCodeQuery) GroupBy(field string, fields ...string) *UserPromoCodeGroupBy {
	upcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserPromoCodeGroupBy{build: upcq}
	grbuild.flds = &upcq.ctx.Fields
	grbuild.label = userpromocode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		City string `json:"city,omitempty"`
//	}
//
//	client.UserPromoCode.Query().
//		Select(userpromocode.FieldCity).
//		Scan(ctx, &v)
func (upcq *UserPromoCodeQuery) Select(fields ...string) *UserPromoCodeSelect {
	upcq.ctx.Fields = append(upcq.ctx.Fields, fields...)
	sbuild := &UserPromoCodeSelect{UserPromoCodeQuery: upcq}
	sbuild.label = userpromocode.Label
	sbuild.flds, sbuild.scan = &upcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserPromoCodeSelect configured with the given aggregations.
func (upcq *UserPromoCodeQuery) Aggregate(fns ...AggregateFunc) *UserPromoCodeSelect {
	return upcq.Select().Aggregate(fns...)
}

func (upcq *UserPromoCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range upcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, upcq); err != nil {
				return err
			}
		}
	}
	for _, f := range upcq.ctx.Fields {
		if !userpromocode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upcq.path != nil {
		prev, err := upcq.path(ctx)
		if err != nil {
			return err
		}
		upcq.sql = prev
	}
	return nil
}

func (upcq *UserPromoCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserPromoCode, error) {
	var (
		nodes       = []*UserPromoCode{}
		_spec       = upcq.querySpec()
		loadedTypes = [1]bool{
			upcq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserPromoCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserPromoCode{config: upcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, upcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := upcq.withUser; query != nil {
		if err := upcq.loadUser(ctx, query, nodes, nil,
			func(n *UserPromoCode, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (upcq *UserPromoCodeQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserPromoCode, init func(*UserPromoCode), assign func(*UserPromoCode, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserPromoCode)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (upcq *UserPromoCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upcq.querySpec()
	_spec.Node.Columns = upcq.ctx.Fields
	if len(upcq.ctx.Fields) > 0 {
		_spec.Unique = upcq.ctx.Unique != nil && *upcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, upcq.driver, _spec)
}

func (upcq *UserPromoCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userpromocode.Table,
			Columns: userpromocode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userpromocode.FieldID,
			},
		},
		From:   upcq.sql,
		Unique: true,
	}
	if unique := upcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := upcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpromocode.FieldID)
		for i := range fields {
			if fields[i] != userpromocode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upcq *UserPromoCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upcq.driver.Dialect())
	t1 := builder.Table(userpromocode.Table)
	columns := upcq.ctx.Fields
	if len(columns) == 0 {
		columns = userpromocode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if upcq.sql != nil {
		selector = upcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if upcq.ctx.Unique != nil && *upcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range upcq.predicates {
		p(selector)
	}
	for _, p := range upcq.order {
		p(selector)
	}
	if offset := upcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserPromoCodeGroupBy is the group-by builder for UserPromoCode entities.
type UserPromoCodeGroupBy struct {
	selector
	build *UserPromoCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upcgb *UserPromoCodeGroupBy) Aggregate(fns ...AggregateFunc) *UserPromoCodeGroupBy {
	upcgb.fns = append(upcgb.fns, fns...)
	return upcgb
}

// Scan applies the selector query and scans the result into the given value.
func (upcgb *UserPromoCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, upcgb.build.ctx, "GroupBy")
	if err := upcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPromoCodeQuery, *UserPromoCodeGroupBy](ctx, upcgb.build, upcgb, upcgb.build.inters, v)
}

func (upcgb *UserPromoCodeGroupBy) sqlScan(ctx context.Context, root *UserPromoCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(upcgb.fns))
	for _, fn := range upcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*upcgb.flds)+len(upcgb.fns))
		for _, f := range *upcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*upcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserPromoCodeSelect is the builder for selecting fields of UserPromoCode entities.
type UserPromoCodeSelect struct {
	*UserPromoCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (upcs *UserPromoCodeSelect) Aggregate(fns ...AggregateFunc) *UserPromoCodeSelect {
	upcs.fns = append(upcs.fns, fns...)
	return upcs
}

// Scan applies the selector query and scans the result into the given value.
func (upcs *UserPromoCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, upcs.ctx, "Select")
	if err := upcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPromoCodeQuery, *UserPromoCodeSelect](ctx, upcs.UserPromoCodeQuery, upcs, upcs.inters, v)
}

func (upcs *UserPromoCodeSelect) sqlScan(ctx context.Context, root *UserPromoCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(upcs.fns))
	for _, fn := range upcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*upcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
