// Code generated by ent, DO NOT EDIT.

package user

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldCreditCard holds the string denoting the credit_card field in the database.
	FieldCreditCard = "credit_card"
	// EdgeVehicles holds the string denoting the vehicles edge name in mutations.
	EdgeVehicles = "vehicles"
	// EdgeRides holds the string denoting the rides edge name in mutations.
	EdgeRides = "rides"
	// EdgeUserPromoCodes holds the string denoting the user_promo_codes edge name in mutations.
	EdgeUserPromoCodes = "user_promo_codes"
	// Table holds the table name of the user in the database.
	Table = "users"
	// VehiclesTable is the table that holds the vehicles relation/edge.
	VehiclesTable = "vehicles"
	// VehiclesInverseTable is the table name for the Vehicle entity.
	// It exists in this package in order to avoid circular dependency with the "vehicle" package.
	VehiclesInverseTable = "vehicles"
	// VehiclesColumn is the table column denoting the vehicles relation/edge.
	VehiclesColumn = "owner_id"
	// RidesTable is the table that holds the rides relation/edge.
	RidesTable = "rides"
	// RidesInverseTable is the table name for the Ride entity.
	// It exists in this package in order to avoid circular dependency with the "ride" package.
	RidesInverseTable = "rides"
	// RidesColumn is the table column denoting the rides relation/edge.
	RidesColumn = "rider_id"
	// UserPromoCodesTable is the table that holds the user_promo_codes relation/edge.
	UserPromoCodesTable = "user_promo_codes"
	// UserPromoCodesInverseTable is the table name for the UserPromoCode entity.
	// It exists in this package in order to avoid circular dependency with the "userpromocode" package.
	UserPromoCodesInverseTable = "user_promo_codes"
	// UserPromoCodesColumn is the table column denoting the user_promo_codes relation/edge.
	UserPromoCodesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCity,
	FieldName,
	FieldAddress,
	FieldCreditCard,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
