// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ride is the predicate function for ride builders.
type Ride func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPromoCode is the predicate function for userpromocode builders.
type UserPromoCode func(*sql.Selector)

// Vehicle is the predicate function for vehicle builders.
type Vehicle func(*sql.Selector)

// VehicleLocationHistory is the predicate function for vehiclelocationhistory builders.
type VehicleLocationHistory func(*sql.Selector)
